### ISSUE TITLE
SDG 14 Gutes Beispiel

### ISSUE THREAD

**Issue by Alex-lol-idk** [resteqs/lernkoffer#111]
- erste Seite: "Organisation, die Siegel"
- Geschichte: "Naturschutzorganisation" ; "unter der Marke Iglo verkauft" (geht ja nur um die Firma Unilever i think) ; "Der MSC soll sich vor allem auf die ... Überfischung konzentrieren." ; "gefangen werden, als es" ; "Der MSC entwickelt Richtlinien, die bestimmen, was Fischereien machen müssen, damit ihr Fischfang als nachhaltig gilt." 
- Kriterien und Zertifizierung: würde den Doppelpunkt nach dem Titel noch wegmachen; "wie bereits gesagt, darauf" ; vlt eher "vom Wasser in den Supermarkt"? also ich weiß nicht, ob das mit dem regal so verständlich ist
- Kritik: "2017 sagten sie" ist irgendwie komisch;  vlt eher "2017 merkte diese Organisation an, dass..." ; "Firmen, denen die .. genügen und die ein Konzept" ; "Das reicht Greenpeace nicht, denn laut ihnen werden auch die Richtlinien teilweise..." ; "Zusätzlich kritisiert die Umweltschutzorganisation, dass..." ; "Deshalb wirft sie dem MSC, bei diesem..."
- Mögliche Lösung: "sicher, ihr" ; "Oder ihr habt die Idee gehabt, dass ein Zertifikat, welches eine ökologische Produktion anzeigt, oder das Fairtrade Siegel auch dafür sprechen, dass..."

**Comment by FabiH0903** [comment]
-done-
