### ISSUE TITLE
SDG 7 Spiel_noch nicht fertig korrigiert!

### ISSUE THREAD

**Issue by Alex-lol-idk** [resteqs/lernkoffer#147]
Einleitung: "Aber weißt du auch, mit welchen ..." (Komma einfügen)
Aufgabe "Gleich siehst du ein Feld mit Memory-Karten. Falls du das Spiel nicht kennst: Es geht darum, dass du zuerst eine Karte ziehst, danach eine zweite und dann mit beiden versuchst, ein Pärchen zu bilden." (Punkt setzen, Satzanfang "falls" groß, danach Satz abgeändert) ; Punkt ganz am Ende nach "fließt"
Texte fehlen zu den Karten/Bilder komplett?! sollten eigentlich als Teil vom Memory da sein

**Comment by FabiH0903** [comment]
Soweit fertig.
