### ISSUE TITLE
SDG 13 Quiz gscheid machen

### ISSUE THREAD

**Issue by misterrabenklaue** [resteqs/lernkoffer#26]
Also des ist halt schlimm alt das Ding nur dass wirs nicht vergessen oder so

**Comment by resteqs** [comment]
Ist es gscheid?

**Comment by FabiH0903** [comment]
was meisnt du damit miserabenklaue

**Comment by misterrabenklaue** [comment]
Weiß ich nimmer entweder das DND dings oder dasd Antippspiel warum auch immer oder das wurde gefixed

**Comment by FabiH0903** [comment]
Das sind doch die Spiele.....

**Comment by misterrabenklaue** [comment]
Ja keiune Ahnung ich könnte sie auch verwechselt haben, aber wahrscheinlich wurde es einfach gefixed
