### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by Skydreamer-123** [resteqs/lernkoffer#86]
- [x] Bug: Bei 5 Einstieg ist der Okay Button überdimensional groß
- [x] Zurück button bei ersten Folie

11 Quiz
- [x] -    Frage 4 Fragezeichen

11 Infotext 
- [x] -    Was ist das Problem 1. Seite Busse statt Buse
- [x] -    Was ist das Problem 2. Seite wiederum mit einem r
- [x] -    Wie ist dieses Thema mit uns verbunden Komma zischen gelebt hat und wobei
- [x] -    3. Zeile wasser- … und Müllsystemen

11 FA passt
11 GB 
- [x] -    Anmerkung: 2. Zeile ist es ohne Komma
- [x] -    Schritt 1: „Und … Füllung“ nicht fett dafür die einzelnen Matierialen fett
- [x] -    Schritt 2: kein Komma zwischen Farbe und oder und zwischen möchtest und oder

13 IT 
- [x] -    Einzelne Groß bei letzter Seite

13 Quiz:
- [x] -    2. Seite Komma zwischen produziert und gehen, Diejenigen und die, und nochmal zwischen produziert und gehen
- [x] -    2. Frage: Gase Komma die
- [x] -    Antwort 3. Frage Linienbussen nicht Linienbusen xD
- [x] -    Ideen: Verkehrsmittel Komma wann; Versuche Komma lokal

- [x] Antippspiel 13 falsch verlinkt in der Einleitung, man wird zur Help Seite geleitet
- [x] Antippspiel einf englisch

Umweltschutzkette
- [x] -    Tutorial 1. Seite 3.Zeile Punkt am Ende
- [x] -    2. Seite letzte Zeile kann als kein Komma

5 Quiz v2
- [x] -    Antwort bei Frage 2: Wer Chef wir Komma sollte
- [x] -    Antwort bei Frage 3: hat das Recht Komma sein
- [x] -    Antowort bei Frage 4: egal Komma welches
- [x] -    Antwort bei Frage 5: Schlimmem groß

5 Einstieg
- [x] -    Alle Antorten groß und mit Punkt
- [x] -    Bei Sekretär:in / Politiker / Feuerwehr … noch einfügen

@Informatiker Wer auch immer das machen mag / muss /darf
dat sind die RS Fehler die ich noch gefunden hab
(und beim letzten ein vh vw bug) 

- [x] 5 Einstieg bei Frage Politiker Antwort Falsch ([...]**)**
- [x] SDG 05 Quiz bei der ersten Antwort heißt es "strickt", es muss aber "strikt" heißen
- [x] SDG 05 Infotext 2. Seite, es muss "in Folge dessen" heißen, das "in" fehlt

**Comment by FabiH0903** [comment]
SDG05. Einstieg --  Zurück button bei ersten Folie und dein Antippspiel @Skydreamer-123 musst du machen!

**Comment by Skydreamer-123** [comment]
- [ ] QuizC. Answertext dynamic!!
- [ ] 12 GB Bilder mittig
- [x] SDG11/FreieArbeit Bild

**Comment by FabiH0903** [comment]
> * [ ]  QuizC. Answertext dynamic!!
> * [ ]  12 GB Bilder mittig
> * [x]  SDG11/FreieArbeit Bild

Mach ich nacher
