### ISSUE TITLE
SDG 11 Anmerkung

### ISSUE THREAD

**Issue by Skydreamer-123** [resteqs/lernkoffer#87]
### IM MPZ Branch

- [x] sdg 11, freie Arbeit: "Papier Arten" -> "Papierarten"
- [x] eine Seite weiter: "jetzt, da du dir ausgedacht hast, wie" Komma!
- [x] selbe Seite: "so kreativ, wie du" Komma!
- [x] nächste Seite: "Strom produziert und auch" -> "Strom produziert. Auch"
- [ ] 
- [ ] 
- [x] sdg 11, gutes Beispiel: "Eine davon ist es wie eine" -> "Eine davon ist, es wie eine"
- [x] nächste Seite: "dann wäre weiß" -> "dann ist weiß"
- [x] selbe Seite: "reflektieren (zurückwerfen) würde und" -> "reflektiert (zurückwirft) und"
- [x] selbe Seite: "Diese würde das Sonnenlicht nämlich aufnehmen" -> "Schwarze Farbe nimmt das Sonnenlicht auf"
- [x] nächste Seite: "Das wäre:" -> "Für das Insektenhotel brauchst du:"
- [x] selbe Seite: "eine Dose" (klein schreiben)
- [x] selbe Seite: "einen Draht" (klein schreiben und Grammatik)
- [x] selbe Seite: "Und natürlich die Füllung" -> "die Füllung"
- [x] "(Wenn du das.... diese weg.)" Satzanfang groß, Satzzeichen
- [x] selbe Seite, mehrmals (!): Vor einem Komma kein Leerzeichen, bspw "Papier ," -> "Papier,"
- [x] selbe Seite: "gut wären." (Satzzeichen!) Den Tipp dann ohne Klammerung als neuer Absatz! In diesem neuen Satz bitte "Nimm" (Satzanfang! Groß!) und "können." (Satzzeichen!)
- [x] nächste Seite: "einen Nagel und einen Hammer" (2x Grammatik!)
- [x] selbe Seite: "optional"
- [x] selbe Seite: "Farbe oder Wolle, wenn du es bunter gestalten willst."
- [x] selbe Seite: "optional: Fäden sowie Perlen oder Knöpfe, wenn du es wie ein Tier gestalten willst, das Beine hat."
- [x] weiter hinten, Schritt 3: "(Wenn du ein Tier mit Beinen..." -> alles in Klammern ein eigenständiger Satz ohne Klammern. Bitte auf korrekte Satzzeichen beim Satz davor und diesem Satz dann achten!
- [x] nächste Seite: "das Loch, was du" -> "das Loch, das du"
- [x] Ein paar Seiten weiter, Schritt 5: "in der Natur (Tipp" -> Tipp nicht in Klammern, sondern als Absatz darunter als eigenständiger Satz. Bitte jeweils dann auf die Satzzeichen achten!
- [ ] 
- [ ] 
- [ ] sdg 11, Infotext, erste Seite: Ich höre nicht / kann nix abspielen
- [x] nächste Seite: "stark zu und damit" -> "stark zu, und damit"
- [x] selbe Seite: "Zersiedelung (dass" -> "Zersiedelung (das heißt, dass"
- [x] nächste Seite: "um die schlechten Wohnbedingungen nicht zu erwähnen" macht keinen Sinn. Ich würde den kompletten Satz ändern zu "in denen die Menschen zum einen unter den schlechten Wohnbedingungen leiden, zusätzlich aber auch keinen... haben."
- [ ] selbe Seite: haben wir auch einen traurigen EG? Ihr redet hier von echten Problemen der Menschen und drunter sitzt EG und jubelt.... Ernsthaft?
- [x] Seite mit uns verbunden: "gelebt hat" -> "lebte", "abgenommen hat" -> "abnahm"
- [x] selbe Seite: "im Jahr 2018" -> "bis zum Jahr 2018"
- [x] selbe Seite: "stand bei" -> "steht aktuell bei"
- [x] selbe Seite: "was ungefähr eine Milliarde Menschen widerspiegelte" -> "was ungefähr einer Milliarde Menschen entspricht" Grammatik und Worttausch!
- [x] nächste Seite: "2019 hatten aus" -> "2019 hatte aus"
- [x] selbe Seite: ""kleinen" öffentlichen Transportmitteln" Grammatik!
- [x] selbe Seite: ""großen" öffentlichen Transportmitteln"" ein Anführungszeichen zuviel
- [x] selbe Seite: 500m und 1000m statt Meter ausgeschrieben.
- [ ] 
- [ ] 
- [x] sdg 11, Spiel: "Der ökologische Fußabdruck zeigt auf, wie umweltbewusst ein Mensch lebt."
- [x] selbe Seite: "Im Folgenden werden verschiedene Entscheidungen, die du triffst, nach ihrer Umweltverträglichkeit bewertet."
- [x] nächste Seite: "Du wirst immer eine Frage..."
- [x] selbe Seite: "während dem Spielen" -> "während des Spiels"
- [x] Frage 3: "Spielzeuge, die" -> "Spielzeug, welche" Grammatik und Wortwechsel!
- [x] Frage 4: "Kein bis ein Mal" -> "nie bis einmal"
- [x] selbe Seite: "zwei- bis dreimal", "viermal oder öfter"
- [ ] Auswertung erste Seite: Was ist das für eine Trennung? Freundlich kann man so nicht trennen!

**Comment by Skydreamer-123** [comment]
Alle SDGs bis Samstag Abend

**Comment by resteqs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SDG 11 auf Bugs überprüfen](https://trello.com/c/Hh0iXAF4/26-sdg-11-auf-bugs-%C3%BCberpr%C3%BCfen)
