### ISSUE TITLE
SDG 11 Audio geht ned

### ISSUE THREAD

**Issue by resteqs** [resteqs/lernkoffer#88]
Audio läuft bei SDG11 ned (laut lb). Bitte überprüfen und korrigieren

**Comment by FabiH0903** [comment]
Unwichtig vorerst, beim MPZ build erstmal raus

**Comment by resteqs** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SDG 11 Audio Component weg](https://trello.com/c/Fo8mLRvp/37-sdg-11-audio-component-weg)
